-- V2: Core schema for users, events, and reservations.
--
-- Conventions:
--   pk_  primary key         fk_  foreign key        uq_  unique constraint
--   ux_  unique index        ck_  check constraint   ix_  non-unique index
-- Primary keys are UUIDv7, generated by the application.
-- Timestamps are set by the application from an injected Clock.

CREATE TABLE users (
    id              uuid         NOT NULL,
    email           varchar(254) NOT NULL,
    password_hash   varchar(255) NOT NULL,
    display_name    varchar(100) NOT NULL,
    role            varchar(20)  NOT NULL,
    created_at      timestamptz  NOT NULL,
    updated_at      timestamptz  NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_canonical CHECK (email = lower(btrim(email))),
    CONSTRAINT ck_users_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ORGANIZER', 'ADMIN')),
    CONSTRAINT ck_users_updated_after_created CHECK (updated_at >= created_at)
);

COMMENT ON COLUMN users.role IS
    'Additive capabilities: every role can act as an attendee. ORGANIZER adds event '
    'management; ADMIN adds platform administration.';

CREATE TABLE events (
    id                      uuid         NOT NULL,
    organizer_id            uuid         NOT NULL,
    name                    varchar(200) NOT NULL,
    description             text,
    capacity                integer      NOT NULL,
    reserved_count          integer      NOT NULL DEFAULT 0,
    status                  varchar(20)  NOT NULL,
    time_zone               varchar(64)  NOT NULL,
    registration_open_at    timestamptz  NOT NULL,
    registration_close_at   timestamptz  NOT NULL,
    starts_at               timestamptz  NOT NULL,
    ends_at                 timestamptz  NOT NULL,
    cancelled_at            timestamptz,
    created_at              timestamptz  NOT NULL,
    updated_at              timestamptz  NOT NULL,

    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_organizer FOREIGN KEY (organizer_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_events_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_events_capacity_positive CHECK (capacity > 0),
    CONSTRAINT ck_events_reserved_count_within_capacity
        CHECK (reserved_count >= 0 AND reserved_count <= capacity),
    CONSTRAINT ck_events_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    CONSTRAINT ck_events_cancelled_at_matches_status
        CHECK ((status = 'CANCELLED') = (cancelled_at IS NOT NULL)),
    CONSTRAINT ck_events_registration_window
        CHECK (registration_open_at < registration_close_at),
    CONSTRAINT ck_events_registration_closes_before_start
        CHECK (registration_close_at <= starts_at),
    CONSTRAINT ck_events_time_order CHECK (starts_at < ends_at),
    CONSTRAINT ck_events_updated_after_created CHECK (updated_at >= created_at),
    CONSTRAINT ck_events_cancelled_after_created
        CHECK (cancelled_at IS NULL OR cancelled_at >= created_at)
);

COMMENT ON COLUMN events.reserved_count IS
    'Number of CONFIRMED reservations. Modified only by conditional atomic UPDATE '
    'in the same transaction as the reservation row change; never by entity save.';

CREATE INDEX ix_events_organizer_id ON events (organizer_id);

CREATE TABLE reservations (
    id              uuid        NOT NULL,
    event_id        uuid        NOT NULL,
    user_id         uuid        NOT NULL,
    status          varchar(20) NOT NULL,
    created_at      timestamptz NOT NULL,
    cancelled_at    timestamptz,

    CONSTRAINT pk_reservations PRIMARY KEY (id),
    CONSTRAINT fk_reservations_event FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reservations_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_reservations_status CHECK (status IN ('CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_reservations_cancelled_at_matches_status
        CHECK ((status = 'CANCELLED') = (cancelled_at IS NOT NULL)),
    CONSTRAINT ck_reservations_cancelled_after_created
        CHECK (cancelled_at IS NULL OR cancelled_at >= created_at)
);

-- At most one capacity-consuming reservation per user per event; history is preserved.
CREATE UNIQUE INDEX ux_reservations_active_user_event
    ON reservations (event_id, user_id)
    WHERE status = 'CONFIRMED';

CREATE INDEX ix_reservations_user_created_at
    ON reservations (user_id, created_at);
